### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by sigboe** [Destiny1984/XCI-Cutter#1]
Would you consider porting this to Linux?

Dont need a UI :smile:

**Comment by Destiny1984** [comment]
Hello!

Actually i was thinking about a commandline tool. But currently haven't got time.
(Real life problems: job, wife, kids, building a house ...)

Unfortunately i currently haven't got a linux machine for software development.
You can try to compile my sourcecode with mono (vbnc), but it might need some tweaks to run.

**Comment by AnalogMan151** [comment]
@sigboe Here you go: https://github.com/AnalogMan151/XCI_Trimmer
