### ISSUE TITLE
[suggestion] remove single file processing

### ISSUE THREAD

**Issue by DavidBabel** [Destiny1984/XCI-Cutter#11]
Since it's very handy to drag and drop files and folder on Batch processing, i'm not sure the original feature of "one by one" file is still really usefull.

**Comment by Destiny1984** [comment]
The single file processing offers a few features that batch processing doesn't.
Like displaying the cartridge and datasizes, specifying destination-files.

Theres no need to remove it. 
You can just ignore it, if you don't use it :-)
