### ISSUE TITLE
Confusing name

### ISSUE THREAD

**Issue by AnalogMan151** [Destiny1984/XCI-Cutter#2]
Looking at the name alone, I would assume this cut the rom into multiple files, perhaps for use with FAT32 filesystems, but instead it's actually a trimmer. I propose a name change for the app. Examples of other people making the same mistake: https://gbatemp.net/threads/the-cons-of-using-sx-os.504848/

**Comment by Destiny1984** [comment]
"Looking at the name alone" is never a good idea, no matter what program you use. 

Everyone should be smart enough to read the describtion.
That guy over on GBAtemp linked to my thread without even reading it.
I've printed its function in **bold**, easy to read and understand.

As i explained: It cuts off unused space. 
You might call it trimming. 
All in all it's just a name.

You're welcome to create your own fork with a different name (and maybe added functions).

**Comment by AnalogMan151** [comment]
Done. No fancy UI, but it works cross platform and can be scripted for batch processing.

https://github.com/AnalogMan151/XCI_Trimmer

**Comment by Destiny1984** [comment]
Good job! 
I like the way how you calculate the actual cartridge size. 
I've just hardcoded the values.

Batch processing is still on my todo list.
I will implement it whenever i'll find the time to do so.
