### ISSUE TITLE
Suggestion for byte-perfect trim

### ISSUE THREAD

**Issue by xem** [Destiny1984/XCI-Cutter#3]
How about reading the XCI file from the very end and remove all the "FF" bytes you find until you reach a non-FF byte?

It would make games like Snipperclips trimmable.

You could make this operation optional (like a "super-trim" checkbox)

Cheers!

**Comment by Destiny1984** [comment]
No that won't work.

Have you checked the actual Snipperclips dump?
The (unknown) data reaches the end of the file. There's nothing to trim after it.

And furthermore VB.net binaryreaders (and writers) can only read forward.
You might force them to read backwards by seeking two bytes back after every byte read.
But that would degrade performance.

**Comment by xem** [comment]
Ah, alright! Nothing to change then. Thanks for this great tool!
