### ISSUE TITLE
Add recursive folder search

### ISSUE THREAD

**Issue by DavidBabel** [Destiny1984/XCI-Cutter#6]
the batch feature is great, but a folder recursive search maybe a great option to have

**Comment by getraid** [comment]
I've done it here: https://github.com/getraid/XCI-Cutter. I attached the build binary below.
[XCI Cutter.zip](https://github.com/Destiny1984/XCI-Cutter/files/2066099/XCI.Cutter.zip)

**Comment by DavidBabel** [comment]
Good job boy !

**Comment by getraid** [comment]
It was merged into master -> https://github.com/Destiny1984/XCI-Cutter/pull/8. Can be closed.
