### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by nate2014jatc** [Destiny1984/XCI-Cutter#7]
Howdy!

I was wondering if Linux support is on your roadmap at all.
I have a home server that I like to throw my workloads at, and being able to batch process XCI files from the server would be amazing

**Comment by Destiny1984** [comment]
I'm sorry, but that has been asked before in issue #1 

I haven't got a developement machine for linux.
You could try the python script  by @AnalogMan151
https://github.com/AnalogMan151/XCI_Trimmer
